export enum StatusEmprestimo {
  ANDAMENTO = 'ANDAMENTO',
  DEVOLVIDO = 'DEVOLVIDO',
  ATRASADO = 'ATRASADO',
}

export enum StatusExemplar {
  DISPONIVEL = 'DISPONIVEL',
  EMPRESTADO = 'EMPRESTADO',
  RESERVADO = 'RESERVADO',
  MANUTENCAO = 'MANUTENCAO',
  EXTRAVIADO = 'EXTRAVIADO',
}
